# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69c0458eea324b9d102d25e0739a10936e8ed840e9d64fefc813405a1df08ae55e3c9824e87e4e3f9ccc302eda9fb9270b0bc4ff1992c1b6e875c16f81493acd

test:
  secret_key_base: 428f076cf7dfd450a0a5d3e02be58ad587bb39440a922320da2f63cc71e6d0cc49808c27f597b68cdfbf2b20c2a95e8e91c74ad4ea36fc3b16de10576b6b32a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
